config/routes.rb
Rails.application.routes.draw do

  root 'main#show'
  get 'characteristics/:id', to: 'characteristics#show', as: 'characteristics'
  get 'skills/:skill_title/lvlups/new', to: 'lvlups#new', as: 'lvlups_new'
  post 'skills/:skill_title/lvlups', to: 'lvlups#create', as: 'lvlups'
  get 'skills/new'
  post 'skills', to: 'skills#create'
  get 'profiles/edit/:id', to: 'profiles#edit', as: 'profile_edit'
  get 'profiles/:id', to: 'profiles#show', as: 'profile'
  get 'auth/facebook/callback', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/characteristic.rb
class Characteristic < ActiveRecord::Base
  belongs_to :skill
  belongs_to :profile
  has_many :lvlups
  validates :skill_id, :profile_id, presence: true
  delegate :title, to: :skill
end

app/models/lvlup.rb
class Lvlup < ActiveRecord::Base
  belongs_to :characteristic
  validates :description, :characteristic_id, presence: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_many :characteristics
  has_many :skills, through: :characteristics

  def self.find_or_create_from_auth_hash(auth_hash)
    find_or_initialize_by(uid: auth_hash.uid).tap do |user|
      user.uid = auth_hash.uid
      user.nickname = auth_hash.info.name
      user.image = auth_hash.info.image
      user.url = auth_hash.info.urls.Facebook
      user.oauth_token = auth_hash.credentials.token
      user.oauth_expires_at = Time.at(auth_hash.credentials.expires_at)
      user.save!
    end
  end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  include PgSearch

  has_many :characteristics
  has_many :profiles, through: :characteristics
  has_many :lvlups, through: :characteristics
  validates :title, presence: true, uniqueness: true

  pg_search_scope :search, against: :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user=(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= Profile.find(session[:user_id]) if session[:user_id]
  end

  def authenticate
    redirect_to root_path unless current_user
  end

  helper_method :current_user
end

app/controllers/characteristics_controller.rb
class CharacteristicsController < ApplicationController
  def show
    @characteristic = Characteristic.find(params[:id])
    @page_title = @characteristic.title
  end
end

app/controllers/lvlups_controller.rb
class LvlupsController < ApplicationController
  before_action :authenticate

  def new
    @lvlup = Lvlup.new
    skill = Skill.find_by_title!(params[:skill_title])
    @characteristic_id = Characteristic.where(profile_id: current_user.id, skill_id: skill.id).first.id
  end

  def create
    @lvlup = Lvlup.new(permited_params)
    if @lvlup.save
      redirect_to profile_edit_path(current_user)
    else
      render 'new'
    end
  end

  private

  def permited_params
    params.require(:lvlup).permit(:description, :characteristic_id)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def show
    redirect_to profile_edit_path(current_user) if current_user
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate, only: [:edit]

  def show
    @profile = Profile.find(params[:id])
    @page_title = @profile.nickname
  end

  def edit
    @profile = Profile.find(current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = Profile.find_or_create_from_auth_hash(auth_hash)
    self.current_user = user
    redirect_to profile_edit_path(user)
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :authenticate

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.create_with(permited_params).find_or_create_by(title: params[:skill][:title])
    if @skill.errors.any?
      render 'new'
    else
      @skill.profiles << current_user
      redirect_to profile_edit_path(current_user)
    end
  end

  private

  def permited_params
    params.require(:skill).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    @page_title || t(params['controller'] + params['action'])
  end

  def shvetsovdm_profile
    shvetsovdm = Profile.find_by(nickname: 'Dmitry Shvetsov')
    profile_path shvetsovdm
  end
end

app/views/characteristics/show.html.erb
<h2>List of lvlups</h2>
<ul class="list-unstyled">
  <% @characteristic.lvlups.each_with_index do |lvlup, index| %>
    <li class="panel panel-default">
      <div class="panel-heading">
        <%= index + 1 %> level
      </div>
      <div class="panel-body">
        <%= lvlup.description %>
      </div>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>lvlup proto</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <!-- Custom CSS -->
  <style>
  body {
      padding-top: 70px;
      /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
  }
  </style>
</head>
<body>
  <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <% if current_user %>
                  <a class="navbar-brand" href="/">lvlup / <%= current_user.nickname %></a>
                <% else %>
                  <a class="navbar-brand" href="/">lvlup</a>
                <% end %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <% if current_user %>
                      <li>
                          <%= link_to 'signout', signout_path %>
                      </li>
                    <% end %>
                    <li>
                      <%= link_to 'about', page_path('about') %>
                    </li>
                    <li>
                      <%= link_to 'source code', t('source_code_link') %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <div class="page-header">
                  <h1><%= page_title %></h1>
                </div>
                <%= yield %>
            </div>
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

  <%= console if Rails.env.development? %>
  
  <!-- google analytics -->
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-47078794-3', 'auto');
  ga('send', 'pageview');
  </script>
</body>
</html>

app/views/lvlups/new.html.erb
<div class="row">
  <div class="col-lg-6">
    <%= form_for @lvlup do |f| %>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, row: 3, cols: 50, class: 'form-control' %>
      </div>
      <%= f.hidden_field :characteristic_id, value: @characteristic_id %>
      <%= f.submit 'Submit', class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

app/views/main/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="jumbotron">
      <p>
        <%= t('info') %>
      </p>
      <p>
        As an example you can check <%= link_to 'my profile', shvetsovdm_profile %>
      </p>
      <p>
        <%= link_to t('facebook_login'), '/auth/facebook', id: 'sign_in', class: 'btn btn-primary btn-lg' %>
      </p>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<div class="row">
  <div class="col-md-6">
    <p>
      <%= t('disclaimer') %>
    </p>
    <p>
      <%= t('info') %>
    </p>
    <p>
      by <a href="http://shvetsovdm.github.io">Dmitry Shvetsov</a>, email: <a href="mailto:shvetsovdm@gmail.com">shvetsovdm@gmail.com</a>
    </p>
    <p>
      Source code available on <a href="https://github.com/shvetsovdm/lvlup_proto">github</a>.
    </p>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= link_to 'link to share', profile_path(current_user) %> (for now you can only share your profile with this link)
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <h2>List of skills</h2>
    <ul class="list-group">
      <% @profile.characteristics.each do |char| %>
        <li class="list-group-item">
          <%= link_to char.title, characteristics_path(char) %>
          <span class="label label-default"><%= char.lvlups.count %></span>
          <%= link_to 'lvlup', lvlups_new_path(skill_title: char.title), class: 'btn btn-default btn-sm' %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <%= link_to 'add skill', skills_new_path, class: 'btn btn-default btn-lg' %>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h2>List of skills</h2>
    <ul class="list-group">
      <% @profile.characteristics.each do |char| %>
        <li class="list-group-item">
          <%= link_to char.title, characteristics_path(char) %>
          <span class="label label-default"><%= char.lvlups.count %></span>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/skills/new.html.erb
<div class="row">
  <div class="col-lg-6">
    <%= form_for @skill do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-default' %>
    <% end %>
  </div>
</div>